FROM arm32v7/debian:buster

RUN apt-get update && apt-get install -y curl build-essential cmake libasound2-dev
RUN (curl -ksS https://curl.haxx.se/ca/cacert.pem | tee /etc/ssl/certs/cacert.pem) && update-ca-certificates -f
RUN curl -sSL https://deb.nodesource.com/setup_13.x | bash -
RUN (curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -) && \
  (echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list) && \
  apt-get update && apt-get install -y yarn
